// <auto-generated />
using AnaBellaApp.ProductAPI.Model.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AnaBellaApp.ProductAPI.Migrations
{
    [DbContext(typeof(MySQLContext))]
    [Migration("20250113001508_SeedProductAndCategoryDataTable")]
    partial class SeedProductAndCategoryDataTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("AnaBellaApp.ProductAPI.Model.Category", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("category");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Description = "Bermudas em geral",
                            Name = "Bermudas"
                        },
                        new
                        {
                            Id = 2L,
                            Description = "Camisetas e blusas em geral",
                            Name = "Camisetas e Blusas"
                        });
                });

            modelBuilder.Entity("AnaBellaApp.ProductAPI.Model.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CategoryId")
                        .HasColumnType("bigint")
                        .HasColumnName("category_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("description");

                    b.Property<string>("ImageURL")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("image_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("price");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("product");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CategoryId = 1L,
                            Description = "Bermuda linho com elastano. Tamanho 40 ao 48",
                            ImageURL = "https://github.com/trodrigo/AnaBellaApp/blob/master/AnaBellaImages/bermuda_linho_elastano.jpg",
                            Name = "Bermuda linho",
                            Price = 69.9m
                        },
                        new
                        {
                            Id = 2L,
                            CategoryId = 2L,
                            Description = "Blusa canelada com manga tamanho único regular",
                            ImageURL = "https://github.com/trodrigo/AnaBellaApp/blob/master/AnaBellaImages/blusa_canelada.jpg",
                            Name = "Blusa canelada",
                            Price = 69.9m
                        },
                        new
                        {
                            Id = 3L,
                            CategoryId = 2L,
                            Description = "Regata canelada com manga tamanho único regular",
                            ImageURL = "https://github.com/trodrigo/AnaBellaApp/blob/master/AnaBellaImages/regata_canelada.jpg",
                            Name = "Regata canelada",
                            Price = 69.9m
                        });
                });

            modelBuilder.Entity("AnaBellaApp.ProductAPI.Model.Product", b =>
                {
                    b.HasOne("AnaBellaApp.ProductAPI.Model.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("AnaBellaApp.ProductAPI.Model.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
